# Generated by Django 2.1.5 on 2019-02-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(default='andika.nugraha@detik.com', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='message',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='lead',
            name='name',
            field=models.TextField(default='User', max_length=100),
        ),
    ]
