# Generated by Django 2.1.5 on 2019-02-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20190207_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='message',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
